# Generated by Django 5.2.8 on 2025-11-26 23:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0006_usersettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="step",
            name="content",
            field=models.TextField(help_text="Step instructions"),
        ),
    ]
