# Generated by Django 5.2.8 on 2025-11-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0007_alter_step_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersettings",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("de", "Deutsch")],
                default="en-us",
                help_text="Preferred language for the interface",
                max_length=10,
            ),
        ),
    ]
