# Generated by Django 5.2.8 on 2025-12-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0008_alter_usersettings_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="url",
            field=models.TextField(blank=True, help_text="Source URL if recipe is from the web"),
        ),
    ]
