# Generated by Django 5.2.8 on 2025-12-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0009_alter_recipe_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="locale",
            field=models.CharField(
                choices=[
                    ("en-us", "English (United States) - MM/DD/YYYY, 1,234.56"),
                    ("en-gb", "English (United Kingdom) - DD/MM/YYYY, 1,234.56"),
                    ("de-de", "Deutsch (Deutschland) - DD.MM.YYYY, 1.234,56"),
                    ("fr-fr", "Français (France) - DD/MM/YYYY, 1 234,56"),
                    ("es-es", "Español (España) - DD/MM/YYYY, 1.234,56"),
                    ("it-it", "Italiano (Italia) - DD/MM/YYYY, 1.234,56"),
                ],
                default="en-us",
                help_text="Preferred format for dates, times, and numbers",
                max_length=10,
            ),
        ),
    ]
