# Generated by Django 5.2.8 on 2026-06-13 20:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0010_usersettings_locale"),
    ]

    operations = [
        migrations.AddField(
            model_name="step",
            name="timer",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="Optional timer duration in minutes", null=True
            ),
        ),
    ]
