# Generated by Django 5.2.8 on 2026-06-13 21:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0011_step_timer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="step",
            name="timer",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Optional timer duration in minutes",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
