# Generated by Django 5.2.8 on 2025-11-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AISettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "api_url",
                    models.URLField(
                        help_text="URL of the LLM API endpoint (e.g., https://api.openai.com/v1/chat/completions)"
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        help_text="API key for authentication", max_length=500
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        help_text="Model name (e.g., gpt-4, claude-3-sonnet-20240229)",
                        max_length=200,
                    ),
                ),
                (
                    "max_tokens",
                    models.PositiveIntegerField(
                        default=4096, help_text="Maximum tokens for the response"
                    ),
                ),
                (
                    "temperature",
                    models.FloatField(
                        default=0.7,
                        help_text="Temperature for response randomness (0.0 to 2.0)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "AI Settings",
                "verbose_name_plural": "AI Settings",
            },
        ),
    ]
