# Generated by Django 5.2.8 on 2025-11-21 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_aisettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aisettings",
            name="api_key",
            field=models.CharField(
                blank=True,
                help_text="API key for authentication",
                max_length=500,
                null=True,
            ),
        ),
    ]
