# Generated by Django 5.2.8 on 2025-11-22 13:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0004_mealplan_mealplanentry"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "input_type",
                    models.CharField(choices=[("text", "Text"), ("html", "HTML"), ("url", "URL")], max_length=10),
                ),
                ("input_content", models.TextField(help_text="The text, HTML, or URL to extract recipe from")),
                ("instructions", models.TextField(blank=True, help_text="Optional additional instructions for the AI")),
                ("result_data", models.JSONField(blank=True, help_text="Extracted recipe data as JSON", null=True)),
                ("error_message", models.TextField(blank=True, help_text="Error message if job failed")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "seen",
                    models.BooleanField(default=False, help_text="Whether user has seen this completed/failed job"),
                ),
                ("timeout", models.PositiveIntegerField(help_text="Timeout in seconds for this job")),
            ],
            options={
                "verbose_name": "AI Job",
                "verbose_name_plural": "AI Jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="aisettings",
            name="timeout",
            field=models.PositiveIntegerField(
                default=60,
                help_text="Timeout in seconds (10-600). Jobs with timeout > 10s run in background.",
                validators=[
                    django.core.validators.MinValueValidator(10),
                    django.core.validators.MaxValueValidator(600),
                ],
            ),
        ),
    ]
